# Generated by Django 4.2.2 on 2023-07-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TiredPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_key", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
