# Generated by Django 4.2.2 on 2023-07-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet_api", "0004_rename_customer_apikeytiredperson_name_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="APIKeyTiredPerson",
        ),
        migrations.DeleteModel(
            name="TiredPerson",
        ),
    ]
